//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 04:32:34 PM CET 
//


package com.redfin.sitemapgenerator.jaxbModel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.aldo.wrapperGazzettaWebConcorsi.server.sitemap.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.aldo.wrapperGazzettaWebConcorsi.server.sitemap.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sitemapindex }
     * 
     */
    public Sitemapindex createSitemapindex() {
        return new Sitemapindex();
    }

    /**
     * Create an instance of {@link TSitemap }
     * 
     */
    public TSitemap createTSitemap() {
        return new TSitemap();
    }

}
